In [1]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

---

## Split the Data into Training and Testing Sets

### Step 1: Read the `lending_data.csv` data from the `Resources` folder into a Pandas DataFrame.

In [2]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
# YOUR CODE HERE!
df = pd.read_csv('lending_data.csv')
# Review the DataFrame
# YOUR CODE HERE!
df.head()

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  loan_status  
0                 1       22800            0  
1                 0       13600            0  
2                 0       16100            0  
3                 1       22700            0  
4                 1       23000            0

### Step 2: Create the labels set (`y`)  from the “loan_status” column, and then create the features (`X`) DataFrame from the remaining columns.

In [3]:
# Separate the data into labels and features

# Separate the y variable, the labels
# YOUR CODE HERE!]
y = df['loan_status']
# Separate the X variable, the features
# YOUR CODE HERE!
X = df.drop(columns='loan_status')

In [4]:
# Review the y variable Series
# YOUR CODE HERE!
y.head()

0    0
1    0
2    0
3    0
4    0
Name: loan_status, dtype: int64

In [5]:
# Review the X variable DataFrame
# YOUR CODE HERE!
X.head()

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  
0                 1       22800  
1                 0       13600  
2                 0       16100  
3                 1       22700  
4                 1       23000

### Step 3: Check the balance of the labels variable (`y`) by using the `value_counts` function.

In [6]:
# Check the balance of our target values
# YOUR CODE HERE!
y.value_counts()

0    75036
1     2500
Name: loan_status, dtype: int64

### Step 4: Split the data into training and testing datasets by using `train_test_split`.

In [8]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
# Assign a random_state of 1 to the function
# YOUR CODE HERE!
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

---

## Create a Logistic Regression Model with the Original Data

###  Step 1: Fit a logistic regression model by using the training data (`X_train` and `y_train`).

In [30]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
# YOUR CODE HERE!
logistic_regression_model = LogisticRegression(random_state=1)
logistic_regression_model

# Fit the model using training data
# YOUR CODE HERE!
lr_model = logistic_regression_model.fit(X_train, y_train)

### Step 2: Save the predictions on the testing data labels by using the testing feature data (`X_test`) and the fitted model.

In [14]:
# Make a prediction using the testing data
# YOUR CODE HERE!
training_predictions = lr_model.predict(X_train)

testing_predictions = lr_model.predict(X_test)

### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [32]:
# Print the balanced_accuracy score of the model
# YOUR CODE HERE!
from sklearn.metrics import balanced_accuracy_score
# Display the accuracy score for the test dataset.
print('train accuracy',balanced_accuracy_score(y_train, training_predictions))
print('test accuracy',balanced_accuracy_score(y_test, testing_predictions))

train accuracy 0.9445612665920358
test accuracy 0.9442676901753825


In [19]:
# Generate a confusion matrix for the model
# YOUR CODE HERE!
train_matrix = confusion_matrix(y_train, training_predictions)
test_matrix = confusion_matrix(y_test, testing_predictions)

print(train_matrix)
print(test_matrix)

[[55980   297]
 [  198  1677]]
[[18679    80]
 [   67   558]]


In [23]:
# Print the classification report for the model
# YOUR CODE HERE!
training_report = classification_report(y_train, training_predictions)

testing_report = classification_report(y_test, testing_predictions)

print('training')
print(training_report)
print('----------------------------------------------')
print('testing')
print(testing_report)

training
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     56277
           1       0.85      0.89      0.87      1875

    accuracy                           0.99     58152
   macro avg       0.92      0.94      0.93     58152
weighted avg       0.99      0.99      0.99     58152

----------------------------------------------
testing
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     18759
           1       0.87      0.89      0.88       625

    accuracy                           0.99     19384
   macro avg       0.94      0.94      0.94     19384
weighted avg       0.99      0.99      0.99     19384



### Step 4: Answer the following question.

**Question:** How well does the logistic regression model predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** Precision looks great for high-risk and healthy predictions. A precision of 1 for '0' means no False Positives and a high recall of 1 for '0' means no false negatives either. We do well with the healthy loans. For flagging the high-risk roans, the precision and recall drops. .99 Accuracy is pretty good along with the .88 for F1 meaning 88% of our positive predictions (they are high-risk) were correct.   

---

## Predict a Logistic Regression Model with Resampled Training Data

### Step 1: Use the `RandomOverSampler` module from the imbalanced-learn library to resample the data. Be sure to confirm that the labels have an equal number of data points. 

In [25]:
# Import the RandomOverSampler module form imbalanced-learn
from imblearn.over_sampling import RandomOverSampler

# Instantiate the random oversampler model
# # Assign a random_state parameter of 1 to the model
# YOUR CODE HERE!
ros = RandomOverSampler(random_state=1)
# Fit the original training data to the random_oversampler model
# YOUR CODE HERE!

X_res, y_res = ros.fit_resample(X_train, y_train)

In [27]:
# Count the distinct values of the resampled labels data
# YOUR CODE HERE!
y_res.value_counts()

0    56277
1    56277
Name: loan_status, dtype: int64

### Step 2: Use the `LogisticRegression` classifier and the resampled data to fit the model and make predictions.

In [31]:
# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
# YOUR CODE HERE!
ros_model = LogisticRegression(random_state=1)
# Fit the model using the resampled training data
# YOUR CODE HERE!
ros_model = logistic_regression_model.fit(X_res, y_res)
# Make a prediction using the testing data
# YOUR CODE HERE!
ros_training_predictions = lr_model.predict(X_res)

ros_testing_predictions = lr_model.predict(X_test)

### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [33]:
# Print the balanced_accuracy score of the model 
# YOUR CODE HERE!
from sklearn.metrics import balanced_accuracy_score
# Display the accuracy score for the test dataset.
print('train accuracy',balanced_accuracy_score(y_res, ros_training_predictions))
print('test accuracy',balanced_accuracy_score(y_test, ros_testing_predictions))

train accuracy 0.994180571103648
test accuracy 0.9959744975744975


In [34]:
# Generate a confusion matrix for the model
# YOUR CODE HERE!
ros_train_matrix = confusion_matrix(y_res, ros_training_predictions)
ros_test_matrix = confusion_matrix(y_test, ros_testing_predictions)

print(ros_train_matrix)
print(ros_test_matrix)

[[55945   332]
 [  323 55954]]
[[18668    91]
 [    2   623]]


In [35]:
# Print the classification report for the model
# YOUR CODE HERE!
ros_training_report = classification_report(y_res, ros_training_predictions)

ros_testing_report = classification_report(y_test, ros_testing_predictions)

print('training')
print(ros_training_report)
print('----------------------------------------------')
print('testing')
print(ros_testing_report)

training
              precision    recall  f1-score   support

           0       0.99      0.99      0.99     56277
           1       0.99      0.99      0.99     56277

    accuracy                           0.99    112554
   macro avg       0.99      0.99      0.99    112554
weighted avg       0.99      0.99      0.99    112554

----------------------------------------------
testing
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     18759
           1       0.87      1.00      0.93       625

    accuracy                           1.00     19384
   macro avg       0.94      1.00      0.96     19384
weighted avg       1.00      1.00      1.00     19384



### Step 4: Answer the following question

**Question:** How well does the logistic regression model, fit with oversampled data, predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** The new model did even better. It completely removed the occurence of False Negatives and boosted the f1-score from .88 to .93. Precision stayed the same however but the gain in removing false-negatives is a huge win.